[platformio]
default_envs = esp32-devkitv1-transmitter
src_dir = .

[env:esp32-devkitv1-transmitter]
platform = platformio/espressif32@7.0.1
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
