[platformio]
default_envs = esp32-c3-supermini-receiver
src_dir = wireless/receiver

[env:esp32-c3-supermini-receiver]
platform = platformio/espressif32@7.0.1
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    bolderflight/Bolder Flight Systems SBUS@8.1.4
